### PR TITLE
(Tiny PR! Promise!) Turn install commands in README into a list for easier scanning through

### PR DESCRIPTION
**Pull request by PhilippMDoerner**
After reading over it multiple times during helping folks with owlkettle on discord it has begun bothering me on a spiritual level that this list of commands is not expressed as a markdown list :sweat_smile: 

This is a draft for now because @RickBarretto  informed me that they wanted to add some more installation instructions (apparently you also need to install a package called pkg-config?), but by that time I already was 90% done with opening this PR so I decided to just publish this already as a draft and update it when I got the infos about pkg-config from them.

### CODE REVIEW

**Comment by RickBarretto** [comment]
For what I'm seeing, for Windows, it's necessary have the `pkg-config`.
In my case I have this installed inside another packages:
I installed the [`mingw-w64-x86_64-toolchain`](https://packages.msys2.org/groups/mingw-w64-x86_64-toolchain) that has the [`mingw-w64-x86_64-pkgconf`](https://packages.msys2.org/package/mingw-w64-x86_64-pkgconf?repo=mingw64) that provides the [`mingw-w64-x86_64-pkg-config`](https://packages.msys2.org/package/mingw-w64-x86_64-pkg-config).

For what I'm seeing the recommended would be to use the pkgconf. But, in the end of the day the user will need the toolchain anyway due to GCC and binutils (that he probably already have it installed).

**Comment by PhilippMDoerner** [comment]
As discussed [here](https://discord.com/channels/371759389889003530/371759389889003532/1177722683895595109) the current plan is to have a topic in "Discussions" as write up (since how to do it is more of a general "How to use Msys2"-topic than one for owlkettle) and link to that in this PR

**Comment by RickBarretto** [comment]
- A discussion about the installation and configuration of MSYS2 was added at #144.

**Comment by PhilippMDoerner** [comment]
> * @PhilippMDoerner A discussion about the installation and configuration of MSYS2 was added at [How to properly set-up your MSYS2 #144](https://github.com/can-lehmann/owlkettle/discussions/144).

Thanks a ton! Updated the Readme accordingly!

**Comment by RickBarretto** [comment]
> Thanks a ton! Updated the Readme accordingly!

No prob, call me when you need.

**Comment by can-lehmann** [comment]
Thanks, the formatting has actually been bothering me too. Detailed installation instructions & troubleshooting steps for Windows should be added to https://can-lehmann.github.io/owlkettle/docs/installation.html instead of linking to a discussion imo.

**Comment by PhilippMDoerner** [comment]
Coordinated with @RickBarretto [in discord](https://discord.com/channels/371759389889003530/979844494205812806/1178068903834947754) a bit.

The current plan is for this PR to be dead simple and simply link to the installation page (besides the "turn instructions to list" thing).

@RickBarretto can then in a separate PR update the installation.md file with the new information and insights gained (likely adding a "Troubleshooting your MSYS2 setup" section or the like, however he ends up doing it).

**Comment by can-lehmann** [comment]
Sounds good. Thanks to everybody involved!

**Pull request merged**
